#ejercicio de las 48 lineas de codigo
Nc=input("ingresa el nombre de la institucion")
Us=input("Ingresa el nombre del usuario")
print("Bienvenido al usuario",Us,"este es el sistemas de notas de nuestro colegio",Nc,)
print("Cabe aclarar que este es un sistema exclusivo para profesores ya que aqui pueden digitar las notas de los estudiantes")
Nm=("Ingrese aqui el nombre del estudiante")
Materia=(input("Coloca aqui el nombre de la materia"))
nota1=float(input("coloca la primera nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota2=float(input("coloca la segunda nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota3=float(input("coloca la tercera nota, por favor la nota debe de sr de 1.0 a 5.0"))
Promedio=nota1+nota2+nota3/3
print("El promedio del Estudiante",Nm,"es:",Promedio)
Materia1=(input("Coloca aqui el nombre de la materia"))
nota4=float(input("coloca la primera nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota5=float(input("coloca la segunda nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota6=float(input("coloca la tercera nota, por favor la nota debe de sr de 1.0 a 5.0"))
Promedio1=nota4+nota5+nota6/3
print("El promedio del Estudiante",Nm,"es:",Promedio1)
Materia2=(input("Coloca aqui el nombre de la materia"))
nota7=float(input("coloca la primera nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota8=float(input("coloca la segunda nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota9=float(input("coloca la tercera nota, por favor la nota debe de sr de 1.0 a 5.0"))
Promedio2=nota7+nota8+nota9/3
print("El promedio del Estudiante",Nm,"es:",Promedio2)
Materia3=(input("Coloca aqui el nombre de la materia"))
nota10=float(input("coloca la primera nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota11=float(input("coloca la segunda nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota12=float(input("coloca la tercera nota, por favor la nota debe de sr de 1.0 a 5.0"))
Promedio3=nota10+nota11+nota12/3
print("El promedio del Estudiante",Nm,"es:",Promedio3)
Materia4=(input("Coloca aqui el nombre de la materia"))
nota13=float(input("coloca la primera nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota14=float(input("coloca la segunda nota, por favor la nota debe de sr de 1.0 a 5.0"))
nota15=float(input("coloca la tercera nota, por favor la nota debe de sr de 1.0 a 5.0"))
Promedio4=nota13+nota14+nota15/3
print("El promedio del Estudiante",Nm,"es:",Promedio)
print("Notas Finales")
print("El promedio de",Materia,"es:",Promedio)
print("El promedio de",Materia1,"es:",Promedio1)
print("El promedio de",Materia2,"es:",Promedio2)
print("El promedio de",Materia3,"es:",Promedio3)
print("El promedio de",Materia4,"es:",Promedio4)
print(input("oiga parcero de que es Cali o America"))